config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root to: "books#index"
  resources :books
  resources :about, only: :index
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  include PgSearch::Model

  before_save :default_values

  pg_search_scope :term_search,
    against: [:title, :description, :author],
    using: {
      tsearch: { prefix: true }
  }

  def default_values
    if self.image_url.nil? || self.image_url == ""
      self.image_url = ActionController::Base.helpers.asset_path("default_book_image.jpeg")
    end
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:create, :update, :destroy]

  def index
    @books = filter(params[:query])

    sort(@books, params[:order])

    respond_to do |format|
      format.html
      format.json { render json: { books: @books } }
    end
  end
 
  def show
  end

  def edit
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Livro criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Livro atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Livro removido com sucesso.'
  end

  private

    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :description, :pages, :category, :author, :image_url)
    end

    def filter(query)
      return Book.term_search(query) if query.present?
        
      Book.all
    end

    def sort(books, order)
      return if order.nil? || order == ""

      @books = books.order("title #{order}")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<main>
  <div class="album py-5 bg-light">
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"> Projeto Catálogo de Livros</h1>
        <p class="lead text-muted">Este projeto é um desafio técnico proposto pela Zygo em seu processo seletivo para vaga de backend, no qual é necessário construir um sistema simples onde usuários podem acessar e buscar por livros.</p>
        <p>
          <a href="https://github.com/zygotecnologia/zygo-programming-challenges/tree/master/developer/pleno" class="btn btn-primary my-2">Desafio</a>
          <a href="https://gitlab.com/pperussi/books_catalog" class="btn btn-secondary my-2">Código Fonte</a>
        </p>
      </div>
    </div>
  </div>
  </section>
<main>

app/views/books/_book.html.erb
<div class="card shadow-sm m-2 col-md-2 h-250">
  <svg class="bd-placeholder-img card-img-top" width="100%" height="20" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder:
    Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
  </svg><%= image_tag book.image_url, class: 'img-fluid h-75' %>
  <div class="card-body">
    <p class="card-text"><%= book.title %>
      <br>
      <small class="text-muted"><%= book.author %></small>
    </p>
    <div class="d-flex justify-content-between align-items-right">
      <div class="btn-group">
        <button type="button" class="btn btn-sm btn-outline-secondary">
          <%= link_to 'Detalhes', book, style: 'color: gray' %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
 <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <div class='row'>
    <div class='col'>
      <div class="field">
        <%= form.label 'Título' %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label 'Autor' %>
        <%= form.text_field :author, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label 'Páginas' %>
        <%= form.text_field :pages, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label 'Categoria' %>
        <%= form.text_field :category, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label 'URL da Imagem' %>
        <%= form.text_field :image_url, class: "form-control" %>
      </div>
    </div>
    <div class='col'>
      <div class="field">
        <%= form.label 'Descrição' %>
        <%= form.text_area :description, class: "form-control", rows: '8' %>
      </div>

        <div class="actions float-end" style="padding-top: 35px; ">
          <%= form.submit 'Adicionar', class: "btn btn-outline-primary"%>
        </div>
    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<main>
  <div class="album py-5 bg-light">
    <div style="padding-top: 20px;">
      <div class="row justify-content-center">
        <div class="col-md-8">
         <h2>Atualizar Livro</h2>
          <%= render 'form', book: @book %>

        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div style="padding-top: 50px;">
        <div class="row" width="100%" data-controller="search">
          <div class="col-md-12">
            <%= form_with(url: "/", method: :get, data: {action: "input->search#submit"}) do |form| %>
              <%= label_tag(:query, "Filtrar") %>
              <%= text_field_tag(:query, params[:query], data: {target: "search.query"}) %>
              <%= label_tag(:query, "Ordenar por Título:") %>
              <%= form.radio_button :order, "ASC", data: {target: "search.order"} %>
              <%= form.label :age_child, "A-Z" %>
              <%= form.radio_button :order, "DESC", data: {target: "search.order"} %>
              <%= form.label :age_adult, "Z-A" %>
            <% end %>
          </div>

          <div style="padding-top: 50px;">
              <div class="row row-cols-md-4 g-2" id="books" data-search-target="books">
                <%= render @books %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<main>
  <div class="album py-5 bg-light">
    <div style="padding-top: 20px;">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h2>Novo Livro</h2>

          <%= render 'form', book: @book %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="album py-5 bg-light">
    <div style="padding-top: 50px;">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <%= image_tag @book.image_url, size: "230x330" %>
          </div>

          <div class="col-md-9">
            <br>
            <h3>
              <strong><%= @book.title %></strong>
            </h3>
            <p>
              <strong>Autor:</strong>
              <%= @book.author %>
            </p>
            <p>
              <%= @book.description %>
            </p>
            <p>
              <strong>Páginas:</strong>
              <%= @book.pages %>
            </p>
            <p>
              <strong>Categoria:</strong>
              <%= @book.category %>
            </p>

            <div style="padding-top: 50px;">
              <% if admin_signed_in? %>
              <%= link_to 'Editar', edit_book_path(@book), class: 'btn btn-outline-secondary' %>
              <%= link_to 'Remover', @book, method: :delete, data: { confirm: 'Confirma remoção?' }, class: 'btn btn-outline-danger' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Books Catalog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <div class="navbar navbar-dark bg-dark shadow-sm align-items-center d-flex">
      <div class="container">
        <a href="/" class="navbar-brand ">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-book" viewBox="0 0 16 16">
            <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
          </svg>
          <strong href="/">Catálogo de Livros</strong>
        </a>
        <p class="float-end" style="padding-top: 15px;">
        <% if admin_signed_in? %>
          <%= link_to 'Novo Livro', new_book_path, style: 'color: white', class: "btn btn-secondary"%>
          <%= link_to 'Sair', destroy_admin_session_path, method: :delete, style: 'color: white', class: "btn btn-secondary"%>
          <% else %>
          <%= link_to 'Entrar', new_admin_session_path, style: 'color: white', class: "btn btn-secondary"%>
          <% end %>
        </p>
      </div>
    </div>
  </header>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <%= link_to 'Sobre', about_index_path, class: "btn btn-outline-primary"%>
      </p>
      <p class="mb-1">Paula Perussi &copy; Copyleft - Creative Commons</p>
    </div>
  </footer>

  <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>

</html>